spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
    schema: classpath:scripts/schema-h2.sql
    data: classpath:scripts/data-h2.sql
    druid:
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      validation-query: select 1
      remove-abandoned: true
      remove-abandoned-timeout: 300
      filters: stat